### ISSUE TITLE
Trying to Install Embark Addon v1.7.0 to Blender 2.90.1

### ISSUE THREAD

**Issue by firebert85** [EmbarkStudios/blender-tools#8] opened 2020-11-18 13:47 UTC
**Describe the bug**

After installing the addon, when I try to click and Enable v1.7.0 of the addon, I receive the following error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\evans\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-tools-main\__init__.py", line 37, in register
    register_recursive(REGISTER_CLASSES)
  File "C:\Users\evans\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-tools-main\utils\__init__.py", line 60, in register_recursive
    register_recursive(obj.REGISTER_CLASSES)
  File "C:\Users\evans\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-tools-main\utils\__init__.py", line 56, in register_recursive
    bpy.utils.register_class(obj)
ValueError: register_class(...): already registered as a subclass 'EmbarkAddonPreferences'

**To Reproduce**
1. Go to Addons
2. Click Install, and select from disk the latest 1.7.0 zip file of the Embark Addon
3. Click Enable checkbox for addon

**Expected behavior**
Addon to install with no error message.

**Screenshots**

![image](https://user-images.githubusercontent.com/3411843/99538254-b0916680-297a-11eb-8965-0d2094bf5816.png)

**Device:**
 - Windows 10
 - Blender Version 2.90.1

**Additional context**
n/a

**Comment by moppius** [comment] 2020-11-30 14:57
@firebert85 Hmm, did you already have a version of the plugin installed before trying to install this one?

It looks like it's trying to register the same thing twice. can you check your `%APPDATA%\Blender Foundation\Blender\2.90\scripts\addons` folder (paste that path into Windows Explorer) and make sure you don't already have an old version of the plugin installed there?

If there is already a `embark_blender_tools` folder in your `addons` folder, you'll need to delete that before installing the new one.

**Comment by firebert85** [comment] 2020-12-01 01:52
@moppius 
Trying this again on the new 2.91 release, and still get the attached error message every time I try to click the Activate check box
This happens no matter how many times I remove the addon from within Blender and make sure the scripts/addons folder in 2.91 folder is deleted.

![image](https://user-images.githubusercontent.com/3411843/100687289-00463980-334e-11eb-897f-5f3f690ee496.png)

**Comment by firebert85** [comment] 2020-12-01 01:54
This is a new one--I  just got this error message after another complete clean remove/delete from the //scripts/addons folder
![image](https://user-images.githubusercontent.com/3411843/100687434-4d2a1000-334e-11eb-9b0a-31452669beb8.png)

**Comment by firebert85** [comment] 2020-12-12 23:01
For whatever reason--I just went to install this and so far it works.

**Comment by moppius** [comment] 2020-12-14 09:26
Weirdly, I did manage to reproduce this once the other day - I think there is a race condition in registering modules and the update operator, I have a potential fix for it that I'm testing locally.

Thanks for following up!

**Comment by moppius** [comment] 2020-12-15 15:19
Closing this for now, will see if anyone else hits it after the speculative fix in [release 1.7.1](https://github.com/EmbarkStudios/blender-tools/releases/tag/1.7.1).

**Closed by moppius** 2020-12-15 15:19 UTC
Labels: bug
